// Code generated by "stringer -type PathChunkType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PCTEmpty-0]
	_ = x[PCTDot-1]
	_ = x[PCTBrace-2]
	_ = x[PCTIndex-3]
	_ = x[PCTMember-4]
	_ = x[PCTFunction-5]
	_ = x[PCTStar-6]
}

const _PathChunkType_name = "PCTEmptyPCTDotPCTBracePCTIndexPCTMemberPCTFunctionPCTStar"

var _PathChunkType_index = [...]uint8{0, 8, 14, 22, 30, 39, 50, 57}

func (i PathChunkType) String() string {
	if i < 0 || i >= PathChunkType(len(_PathChunkType_index)-1) {
		return "PathChunkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathChunkType_name[_PathChunkType_index[i]:_PathChunkType_index[i+1]]
}
